// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.4
// source: pkg/notification/notification.proto

package notification

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	RequestReservation(ctx context.Context, in *RequestReservationNotification, opts ...grpc.CallOption) (*NotificationResponse, error)
	UpdateUserPreferences(ctx context.Context, in *UserPreferences, opts ...grpc.CallOption) (*UserPreferences, error)
	CreateUserPreferences(ctx context.Context, in *UserPreferences, opts ...grpc.CallOption) (*UserPreferences, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) RequestReservation(ctx context.Context, in *RequestReservationNotification, opts ...grpc.CallOption) (*NotificationResponse, error) {
	out := new(NotificationResponse)
	err := c.cc.Invoke(ctx, "/notification.NotificationService/RequestReservation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) UpdateUserPreferences(ctx context.Context, in *UserPreferences, opts ...grpc.CallOption) (*UserPreferences, error) {
	out := new(UserPreferences)
	err := c.cc.Invoke(ctx, "/notification.NotificationService/UpdateUserPreferences", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) CreateUserPreferences(ctx context.Context, in *UserPreferences, opts ...grpc.CallOption) (*UserPreferences, error) {
	out := new(UserPreferences)
	err := c.cc.Invoke(ctx, "/notification.NotificationService/CreateUserPreferences", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility
type NotificationServiceServer interface {
	RequestReservation(context.Context, *RequestReservationNotification) (*NotificationResponse, error)
	UpdateUserPreferences(context.Context, *UserPreferences) (*UserPreferences, error)
	CreateUserPreferences(context.Context, *UserPreferences) (*UserPreferences, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNotificationServiceServer struct {
}

func (UnimplementedNotificationServiceServer) RequestReservation(context.Context, *RequestReservationNotification) (*NotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestReservation not implemented")
}
func (UnimplementedNotificationServiceServer) UpdateUserPreferences(context.Context, *UserPreferences) (*UserPreferences, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserPreferences not implemented")
}
func (UnimplementedNotificationServiceServer) CreateUserPreferences(context.Context, *UserPreferences) (*UserPreferences, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserPreferences not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_RequestReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestReservationNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).RequestReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.NotificationService/RequestReservation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).RequestReservation(ctx, req.(*RequestReservationNotification))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_UpdateUserPreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPreferences)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).UpdateUserPreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.NotificationService/UpdateUserPreferences",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).UpdateUserPreferences(ctx, req.(*UserPreferences))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_CreateUserPreferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPreferences)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).CreateUserPreferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/notification.NotificationService/CreateUserPreferences",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).CreateUserPreferences(ctx, req.(*UserPreferences))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestReservation",
			Handler:    _NotificationService_RequestReservation_Handler,
		},
		{
			MethodName: "UpdateUserPreferences",
			Handler:    _NotificationService_UpdateUserPreferences_Handler,
		},
		{
			MethodName: "CreateUserPreferences",
			Handler:    _NotificationService_CreateUserPreferences_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/notification/notification.proto",
}
