// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/user/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IdRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdRequest) Reset()         { *m = IdRequest{} }
func (m *IdRequest) String() string { return proto.CompactTextString(m) }
func (*IdRequest) ProtoMessage()    {}
func (*IdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_72e2c27458cc4816, []int{0}
}

func (m *IdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdRequest.Unmarshal(m, b)
}
func (m *IdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdRequest.Marshal(b, m, deterministic)
}
func (m *IdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdRequest.Merge(m, src)
}
func (m *IdRequest) XXX_Size() int {
	return xxx_messageInfo_IdRequest.Size(m)
}
func (m *IdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdRequest proto.InternalMessageInfo

func (m *IdRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UserResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Surname              string   `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	PlaceOfLiving        string   `protobuf:"bytes,6,opt,name=place_of_living,json=placeOfLiving,proto3" json:"place_of_living,omitempty"`
	Role                 string   `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`
	Id                   int64    `protobuf:"varint,8,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_72e2c27458cc4816, []int{1}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserResponse) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *UserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserResponse) GetPlaceOfLiving() string {
	if m != nil {
		return m.PlaceOfLiving
	}
	return ""
}

func (m *UserResponse) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *UserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RegisterRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Surname              string   `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	PlaceOfLiving        string   `protobuf:"bytes,6,opt,name=place_of_living,json=placeOfLiving,proto3" json:"place_of_living,omitempty"`
	Role                 string   `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_72e2c27458cc4816, []int{2}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterRequest) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetPlaceOfLiving() string {
	if m != nil {
		return m.PlaceOfLiving
	}
	return ""
}

func (m *RegisterRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type RegisterResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_72e2c27458cc4816, []int{3}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type LoginRequest struct {
	Username             string     `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string     `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	IdRequest            *IdRequest `protobuf:"bytes,3,opt,name=id_request,json=idRequest,proto3" json:"id_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_72e2c27458cc4816, []int{4}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetIdRequest() *IdRequest {
	if m != nil {
		return m.IdRequest
	}
	return nil
}

type LoginResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_72e2c27458cc4816, []int{5}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func init() {
	proto.RegisterType((*IdRequest)(nil), "user.IdRequest")
	proto.RegisterType((*UserResponse)(nil), "user.UserResponse")
	proto.RegisterType((*RegisterRequest)(nil), "user.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "user.RegisterResponse")
	proto.RegisterType((*LoginRequest)(nil), "user.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "user.LoginResponse")
}

func init() {
	proto.RegisterFile("pkg/user/user.proto", fileDescriptor_72e2c27458cc4816)
}

var fileDescriptor_72e2c27458cc4816 = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x53, 0xcd, 0x8e, 0xd3, 0x40,
	0x0c, 0x6e, 0xba, 0xfd, 0x75, 0xbb, 0x14, 0xcd, 0xc2, 0x2a, 0xca, 0x5e, 0x60, 0x10, 0x88, 0x53,
	0x82, 0xba, 0x47, 0x6e, 0x08, 0x84, 0x90, 0x56, 0x42, 0x0a, 0x70, 0xe1, 0x52, 0xa5, 0x89, 0x1b,
	0x46, 0x9b, 0x64, 0xc2, 0xcc, 0xa4, 0x08, 0xde, 0x90, 0x17, 0xe0, 0x0d, 0x78, 0x0f, 0x34, 0x9e,
	0x24, 0x94, 0x20, 0x71, 0xe7, 0x12, 0xd9, 0x9f, 0xed, 0xf1, 0xf7, 0xc5, 0x36, 0x5c, 0xd4, 0xb7,
	0x79, 0xd4, 0x68, 0x54, 0xf4, 0x09, 0x6b, 0x25, 0x8d, 0x64, 0x13, 0x6b, 0x07, 0x57, 0xb9, 0x94,
	0x79, 0x81, 0x11, 0x61, 0xfb, 0xe6, 0x10, 0x61, 0x59, 0x9b, 0xaf, 0x2e, 0x85, 0x5f, 0xc1, 0xf2,
	0x4d, 0x16, 0xe3, 0xe7, 0x06, 0xb5, 0x61, 0x77, 0x60, 0x2c, 0x32, 0xdf, 0x7b, 0xe0, 0x3d, 0x3d,
	0x8b, 0xc7, 0x22, 0xe3, 0x3f, 0x3c, 0x58, 0x7f, 0xd0, 0xa8, 0x62, 0xd4, 0xb5, 0xac, 0x34, 0x32,
	0x06, 0x93, 0x2a, 0x29, 0x91, 0x52, 0x96, 0x31, 0xd9, 0xcc, 0x87, 0xb9, 0x6e, 0x14, 0xc1, 0x63,
	0x82, 0x3b, 0x97, 0xdd, 0x83, 0x29, 0x96, 0x89, 0x28, 0xfc, 0x33, 0xc2, 0x9d, 0xc3, 0x02, 0x58,
	0x58, 0x5a, 0x54, 0x30, 0xa1, 0x40, 0xef, 0xdb, 0x58, 0x9d, 0x68, 0xfd, 0x45, 0xaa, 0xcc, 0x9f,
	0xba, 0x58, 0xe7, 0xb3, 0x27, 0xb0, 0xa9, 0x8b, 0x24, 0xc5, 0x9d, 0x3c, 0xec, 0x0a, 0x71, 0x14,
	0x55, 0xee, 0xcf, 0x28, 0xe5, 0x9c, 0xe0, 0xb7, 0x87, 0x1b, 0x02, 0x2d, 0x47, 0x25, 0x0b, 0xf4,
	0xe7, 0x8e, 0xa3, 0xb5, 0x5b, 0x61, 0x8b, 0x5e, 0xd8, 0x77, 0x0f, 0x36, 0x31, 0xe6, 0x42, 0x1b,
	0x2b, 0xce, 0x89, 0xff, 0x4f, 0xb5, 0x71, 0x0e, 0x77, 0x7f, 0x4b, 0x69, 0xe7, 0x34, 0x1c, 0xe4,
	0x11, 0xd6, 0x37, 0x32, 0x17, 0x55, 0xa7, 0xf5, 0x94, 0xa7, 0xf7, 0x0f, 0x9e, 0xe3, 0x01, 0xcf,
	0x10, 0x40, 0x64, 0x3b, 0xe5, 0x5e, 0x21, 0xe9, 0xab, 0xed, 0x26, 0xa4, 0x8d, 0xeb, 0xb7, 0x28,
	0x5e, 0x8a, 0xce, 0xe4, 0x5b, 0x38, 0x6f, 0xfb, 0xb6, 0xc4, 0x1e, 0xc2, 0x3a, 0x49, 0x53, 0xd4,
	0x7a, 0x67, 0xe4, 0x2d, 0x56, 0x6d, 0xf3, 0x95, 0xc3, 0xde, 0x5b, 0x68, 0xfb, 0xd3, 0x83, 0x95,
	0x5d, 0xba, 0x77, 0xa8, 0x8e, 0x22, 0x45, 0xf6, 0x1c, 0x16, 0x9d, 0x3e, 0x76, 0xdf, 0xf5, 0x1a,
	0x8c, 0x2e, 0xb8, 0x1c, 0xc2, 0xae, 0x1b, 0x1f, 0xb1, 0x2d, 0x4c, 0x89, 0x00, 0x63, 0x2e, 0xe5,
	0xf4, 0x2f, 0x04, 0x17, 0x7f, 0x60, 0x7d, 0xcd, 0x33, 0x98, 0xbf, 0x46, 0x63, 0x29, 0xb0, 0xa1,
	0xb6, 0xa0, 0x7d, 0xe6, 0xf4, 0x28, 0xf8, 0x88, 0x5d, 0xc3, 0xec, 0x25, 0x16, 0x68, 0xf0, 0xef,
	0x82, 0xcb, 0xd0, 0x5d, 0x5f, 0xd8, 0x5d, 0x5f, 0xf8, 0xca, 0x5e, 0x1f, 0x1f, 0xbd, 0x78, 0xfc,
	0xf1, 0x51, 0x2e, 0xcc, 0xa7, 0x66, 0x1f, 0xa6, 0xb2, 0x8c, 0xb2, 0x6f, 0xb2, 0x12, 0xb2, 0xd6,
	0x51, 0x2a, 0xcb, 0x52, 0x56, 0x51, 0x77, 0xce, 0xfb, 0x19, 0x15, 0x5e, 0xff, 0x0a, 0x00, 0x00,
	0xff, 0xff, 0x36, 0xe7, 0x8a, 0x9d, 0xe1, 0x03, 0x00, 0x00,
}
