// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/accommodation/accommodation.proto

package accommodation

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccommodationRequest struct {
	HostId               int64                 `protobuf:"varint,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Town                 string                `protobuf:"bytes,3,opt,name=town,proto3" json:"town,omitempty"`
	Municipality         string                `protobuf:"bytes,4,opt,name=municipality,proto3" json:"municipality,omitempty"`
	Country              string                `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Amenities            string                `protobuf:"bytes,6,opt,name=amenities,proto3" json:"amenities,omitempty"`
	MinGuests            int64                 `protobuf:"varint,7,opt,name=min_guests,json=minGuests,proto3" json:"min_guests,omitempty"`
	MaxGuests            int64                 `protobuf:"varint,8,opt,name=max_guests,json=maxGuests,proto3" json:"max_guests,omitempty"`
	PricingModel         string                `protobuf:"bytes,9,opt,name=pricing_model,json=pricingModel,proto3" json:"pricing_model,omitempty"`
	ReservationModel     string                `protobuf:"bytes,10,opt,name=reservation_model,json=reservationModel,proto3" json:"reservation_model,omitempty"`
	Images               []*AccommodationImage `protobuf:"bytes,11,rep,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *AccommodationRequest) Reset()         { *m = AccommodationRequest{} }
func (m *AccommodationRequest) String() string { return proto.CompactTextString(m) }
func (*AccommodationRequest) ProtoMessage()    {}
func (*AccommodationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_60c033c297702363, []int{0}
}

func (m *AccommodationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccommodationRequest.Unmarshal(m, b)
}
func (m *AccommodationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccommodationRequest.Marshal(b, m, deterministic)
}
func (m *AccommodationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccommodationRequest.Merge(m, src)
}
func (m *AccommodationRequest) XXX_Size() int {
	return xxx_messageInfo_AccommodationRequest.Size(m)
}
func (m *AccommodationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccommodationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccommodationRequest proto.InternalMessageInfo

func (m *AccommodationRequest) GetHostId() int64 {
	if m != nil {
		return m.HostId
	}
	return 0
}

func (m *AccommodationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AccommodationRequest) GetTown() string {
	if m != nil {
		return m.Town
	}
	return ""
}

func (m *AccommodationRequest) GetMunicipality() string {
	if m != nil {
		return m.Municipality
	}
	return ""
}

func (m *AccommodationRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *AccommodationRequest) GetAmenities() string {
	if m != nil {
		return m.Amenities
	}
	return ""
}

func (m *AccommodationRequest) GetMinGuests() int64 {
	if m != nil {
		return m.MinGuests
	}
	return 0
}

func (m *AccommodationRequest) GetMaxGuests() int64 {
	if m != nil {
		return m.MaxGuests
	}
	return 0
}

func (m *AccommodationRequest) GetPricingModel() string {
	if m != nil {
		return m.PricingModel
	}
	return ""
}

func (m *AccommodationRequest) GetReservationModel() string {
	if m != nil {
		return m.ReservationModel
	}
	return ""
}

func (m *AccommodationRequest) GetImages() []*AccommodationImage {
	if m != nil {
		return m.Images
	}
	return nil
}

type AccommodationImage struct {
	B64Img               string   `protobuf:"bytes,1,opt,name=b64img,proto3" json:"b64img,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccommodationImage) Reset()         { *m = AccommodationImage{} }
func (m *AccommodationImage) String() string { return proto.CompactTextString(m) }
func (*AccommodationImage) ProtoMessage()    {}
func (*AccommodationImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_60c033c297702363, []int{1}
}

func (m *AccommodationImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccommodationImage.Unmarshal(m, b)
}
func (m *AccommodationImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccommodationImage.Marshal(b, m, deterministic)
}
func (m *AccommodationImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccommodationImage.Merge(m, src)
}
func (m *AccommodationImage) XXX_Size() int {
	return xxx_messageInfo_AccommodationImage.Size(m)
}
func (m *AccommodationImage) XXX_DiscardUnknown() {
	xxx_messageInfo_AccommodationImage.DiscardUnknown(m)
}

var xxx_messageInfo_AccommodationImage proto.InternalMessageInfo

func (m *AccommodationImage) GetB64Img() string {
	if m != nil {
		return m.B64Img
	}
	return ""
}

type AccommodationResponse struct {
	AccommodationId      int64    `protobuf:"varint,1,opt,name=accommodation_id,json=accommodationId,proto3" json:"accommodation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccommodationResponse) Reset()         { *m = AccommodationResponse{} }
func (m *AccommodationResponse) String() string { return proto.CompactTextString(m) }
func (*AccommodationResponse) ProtoMessage()    {}
func (*AccommodationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_60c033c297702363, []int{2}
}

func (m *AccommodationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccommodationResponse.Unmarshal(m, b)
}
func (m *AccommodationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccommodationResponse.Marshal(b, m, deterministic)
}
func (m *AccommodationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccommodationResponse.Merge(m, src)
}
func (m *AccommodationResponse) XXX_Size() int {
	return xxx_messageInfo_AccommodationResponse.Size(m)
}
func (m *AccommodationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccommodationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccommodationResponse proto.InternalMessageInfo

func (m *AccommodationResponse) GetAccommodationId() int64 {
	if m != nil {
		return m.AccommodationId
	}
	return 0
}

func init() {
	proto.RegisterType((*AccommodationRequest)(nil), "accommodation.AccommodationRequest")
	proto.RegisterType((*AccommodationImage)(nil), "accommodation.AccommodationImage")
	proto.RegisterType((*AccommodationResponse)(nil), "accommodation.AccommodationResponse")
}

func init() {
	proto.RegisterFile("pkg/accommodation/accommodation.proto", fileDescriptor_60c033c297702363)
}

var fileDescriptor_60c033c297702363 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0xef, 0xd2, 0x40,
	0x10, 0x47, 0xe5, 0x0b, 0x16, 0x3b, 0x48, 0xc4, 0xf5, 0xd7, 0xc6, 0x68, 0x82, 0x45, 0x13, 0x8c,
	0xa4, 0x4d, 0xd0, 0x98, 0x78, 0x14, 0x0f, 0x86, 0x83, 0x97, 0x7a, 0xf3, 0x42, 0xb6, 0xed, 0xa6,
	0x4c, 0x64, 0x77, 0x6b, 0x77, 0x8b, 0xc0, 0x1f, 0x6f, 0x4c, 0xb7, 0x25, 0xb0, 0x90, 0x70, 0xdb,
	0x79, 0xef, 0x43, 0x98, 0xce, 0x0c, 0xbc, 0x2b, 0x7e, 0xe7, 0x11, 0x4b, 0x53, 0x25, 0x84, 0xca,
	0x98, 0x41, 0x25, 0xdd, 0x2a, 0x2c, 0x4a, 0x65, 0x14, 0x19, 0x3a, 0x30, 0xf8, 0x77, 0x07, 0x4f,
	0xbf, 0x9e, 0x93, 0x98, 0xff, 0xa9, 0xb8, 0x36, 0xe4, 0x05, 0xf4, 0xd7, 0x4a, 0x9b, 0x15, 0x66,
	0xb4, 0x33, 0xee, 0x4c, 0xbb, 0xb1, 0x57, 0x97, 0xcb, 0x8c, 0x10, 0xe8, 0x49, 0x26, 0x38, 0xbd,
	0x1b, 0x77, 0xa6, 0x7e, 0x6c, 0xdf, 0x35, 0x33, 0xea, 0xaf, 0xa4, 0xdd, 0x86, 0xd5, 0x6f, 0x12,
	0xc0, 0x43, 0x51, 0x49, 0x4c, 0xb1, 0x60, 0x1b, 0x34, 0x7b, 0xda, 0xb3, 0xce, 0x61, 0x84, 0x42,
	0x3f, 0x55, 0x95, 0x34, 0xe5, 0x9e, 0xde, 0xb7, 0xfa, 0x58, 0x92, 0x57, 0xe0, 0x33, 0xc1, 0x25,
	0x1a, 0xe4, 0x9a, 0x7a, 0xd6, 0x9d, 0x00, 0x79, 0x0d, 0x20, 0x50, 0xae, 0xf2, 0xba, 0x53, 0x4d,
	0xfb, 0xb6, 0x3f, 0x5f, 0xa0, 0xfc, 0x6e, 0x81, 0xd5, 0x6c, 0x77, 0xd4, 0x0f, 0x5a, 0xcd, 0x76,
	0xad, 0x9e, 0xc0, 0xb0, 0x28, 0x31, 0x45, 0x99, 0xaf, 0x84, 0xca, 0xf8, 0x86, 0xfa, 0x4d, 0x6b,
	0x2d, 0xfc, 0x51, 0x33, 0xf2, 0x01, 0x1e, 0x97, 0x5c, 0xf3, 0x72, 0x6b, 0xa7, 0xd2, 0x06, 0xc1,
	0x06, 0x47, 0x67, 0xa2, 0x09, 0x7f, 0x01, 0x0f, 0x05, 0xcb, 0xb9, 0xa6, 0x83, 0x71, 0x77, 0x3a,
	0x98, 0xbf, 0x09, 0xdd, 0xd1, 0x3b, 0x13, 0x5e, 0xd6, 0xc9, 0xb8, 0xfd, 0x41, 0x30, 0x03, 0x72,
	0x6d, 0xc9, 0x73, 0xf0, 0x92, 0xcf, 0x9f, 0x50, 0xe4, 0x76, 0xf8, 0x7e, 0xdc, 0x56, 0xc1, 0x02,
	0x9e, 0x5d, 0x6c, 0x4b, 0x17, 0x4a, 0x6a, 0x4e, 0xde, 0xc3, 0xc8, 0xf9, 0xcb, 0xd3, 0xde, 0x1e,
	0x39, 0x7c, 0x99, 0xcd, 0x0f, 0x17, 0x1b, 0xff, 0xc9, 0xcb, 0x2d, 0xa6, 0x9c, 0x24, 0xf0, 0xe4,
	0x5b, 0xc9, 0x99, 0xe1, 0x8e, 0x25, 0x93, 0x5b, 0xdf, 0xd2, 0x5e, 0xcb, 0xcb, 0xb7, 0xb7, 0x43,
	0x4d, 0x93, 0xc1, 0xbd, 0x45, 0xf8, 0x6b, 0x96, 0xa3, 0x59, 0x57, 0x49, 0x98, 0x2a, 0x11, 0x65,
	0x07, 0x25, 0x51, 0x15, 0x3a, 0xb2, 0x61, 0x19, 0x5d, 0x5d, 0x70, 0xe2, 0xd9, 0xa3, 0xfd, 0xf8,
	0x3f, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xa1, 0x67, 0x5f, 0xdd, 0x02, 0x00, 0x00,
}
