// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/reservation/reservation.proto

package reservation

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReservationStatus int32

const (
	ReservationStatus_RESERVATION_STATUS_UNSPECIFIED ReservationStatus = 0
	ReservationStatus_RESERVATION_STATUS_ACTIVE      ReservationStatus = 1
	ReservationStatus_RESERVATION_STATUS_ACCEPTED    ReservationStatus = 2
	ReservationStatus_RESERVATION_STATUS_DECLINED    ReservationStatus = 3
)

var ReservationStatus_name = map[int32]string{
	0: "RESERVATION_STATUS_UNSPECIFIED",
	1: "RESERVATION_STATUS_ACTIVE",
	2: "RESERVATION_STATUS_ACCEPTED",
	3: "RESERVATION_STATUS_DECLINED",
}

var ReservationStatus_value = map[string]int32{
	"RESERVATION_STATUS_UNSPECIFIED": 0,
	"RESERVATION_STATUS_ACTIVE":      1,
	"RESERVATION_STATUS_ACCEPTED":    2,
	"RESERVATION_STATUS_DECLINED":    3,
}

func (x ReservationStatus) String() string {
	return proto.EnumName(ReservationStatus_name, int32(x))
}

func (ReservationStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7c6c6658ff475ba8, []int{0}
}

type Reservation struct {
	AccommodationId      int64                `protobuf:"varint,1,opt,name=accommodation_id,json=accommodationId,proto3" json:"accommodation_id,omitempty"`
	StartDate            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	NumberOfGuests       int64                `protobuf:"varint,4,opt,name=number_of_guests,json=numberOfGuests,proto3" json:"number_of_guests,omitempty"`
	Status               ReservationStatus    `protobuf:"varint,5,opt,name=status,proto3,enum=reservation.ReservationStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Reservation) Reset()         { *m = Reservation{} }
func (m *Reservation) String() string { return proto.CompactTextString(m) }
func (*Reservation) ProtoMessage()    {}
func (*Reservation) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c6c6658ff475ba8, []int{0}
}

func (m *Reservation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reservation.Unmarshal(m, b)
}
func (m *Reservation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reservation.Marshal(b, m, deterministic)
}
func (m *Reservation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reservation.Merge(m, src)
}
func (m *Reservation) XXX_Size() int {
	return xxx_messageInfo_Reservation.Size(m)
}
func (m *Reservation) XXX_DiscardUnknown() {
	xxx_messageInfo_Reservation.DiscardUnknown(m)
}

var xxx_messageInfo_Reservation proto.InternalMessageInfo

func (m *Reservation) GetAccommodationId() int64 {
	if m != nil {
		return m.AccommodationId
	}
	return 0
}

func (m *Reservation) GetStartDate() *timestamp.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *Reservation) GetEndDate() *timestamp.Timestamp {
	if m != nil {
		return m.EndDate
	}
	return nil
}

func (m *Reservation) GetNumberOfGuests() int64 {
	if m != nil {
		return m.NumberOfGuests
	}
	return 0
}

func (m *Reservation) GetStatus() ReservationStatus {
	if m != nil {
		return m.Status
	}
	return ReservationStatus_RESERVATION_STATUS_UNSPECIFIED
}

type ReserveRequest struct {
	UserId               int64        `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reservation          *Reservation `protobuf:"bytes,2,opt,name=reservation,proto3" json:"reservation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReserveRequest) Reset()         { *m = ReserveRequest{} }
func (m *ReserveRequest) String() string { return proto.CompactTextString(m) }
func (*ReserveRequest) ProtoMessage()    {}
func (*ReserveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c6c6658ff475ba8, []int{1}
}

func (m *ReserveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReserveRequest.Unmarshal(m, b)
}
func (m *ReserveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReserveRequest.Marshal(b, m, deterministic)
}
func (m *ReserveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReserveRequest.Merge(m, src)
}
func (m *ReserveRequest) XXX_Size() int {
	return xxx_messageInfo_ReserveRequest.Size(m)
}
func (m *ReserveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReserveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReserveRequest proto.InternalMessageInfo

func (m *ReserveRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ReserveRequest) GetReservation() *Reservation {
	if m != nil {
		return m.Reservation
	}
	return nil
}

type ReserveResponse struct {
	ReservationId        int64    `protobuf:"varint,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReserveResponse) Reset()         { *m = ReserveResponse{} }
func (m *ReserveResponse) String() string { return proto.CompactTextString(m) }
func (*ReserveResponse) ProtoMessage()    {}
func (*ReserveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c6c6658ff475ba8, []int{2}
}

func (m *ReserveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReserveResponse.Unmarshal(m, b)
}
func (m *ReserveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReserveResponse.Marshal(b, m, deterministic)
}
func (m *ReserveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReserveResponse.Merge(m, src)
}
func (m *ReserveResponse) XXX_Size() int {
	return xxx_messageInfo_ReserveResponse.Size(m)
}
func (m *ReserveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReserveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReserveResponse proto.InternalMessageInfo

func (m *ReserveResponse) GetReservationId() int64 {
	if m != nil {
		return m.ReservationId
	}
	return 0
}

type IdRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdRequest) Reset()         { *m = IdRequest{} }
func (m *IdRequest) String() string { return proto.CompactTextString(m) }
func (*IdRequest) ProtoMessage()    {}
func (*IdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c6c6658ff475ba8, []int{3}
}

func (m *IdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdRequest.Unmarshal(m, b)
}
func (m *IdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdRequest.Marshal(b, m, deterministic)
}
func (m *IdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdRequest.Merge(m, src)
}
func (m *IdRequest) XXX_Size() int {
	return xxx_messageInfo_IdRequest.Size(m)
}
func (m *IdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdRequest proto.InternalMessageInfo

func (m *IdRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ActiveReservationsResponse struct {
	Reservations         []*Reservation `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ActiveReservationsResponse) Reset()         { *m = ActiveReservationsResponse{} }
func (m *ActiveReservationsResponse) String() string { return proto.CompactTextString(m) }
func (*ActiveReservationsResponse) ProtoMessage()    {}
func (*ActiveReservationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c6c6658ff475ba8, []int{4}
}

func (m *ActiveReservationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActiveReservationsResponse.Unmarshal(m, b)
}
func (m *ActiveReservationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActiveReservationsResponse.Marshal(b, m, deterministic)
}
func (m *ActiveReservationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActiveReservationsResponse.Merge(m, src)
}
func (m *ActiveReservationsResponse) XXX_Size() int {
	return xxx_messageInfo_ActiveReservationsResponse.Size(m)
}
func (m *ActiveReservationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActiveReservationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActiveReservationsResponse proto.InternalMessageInfo

func (m *ActiveReservationsResponse) GetReservations() []*Reservation {
	if m != nil {
		return m.Reservations
	}
	return nil
}

func init() {
	proto.RegisterEnum("reservation.ReservationStatus", ReservationStatus_name, ReservationStatus_value)
	proto.RegisterType((*Reservation)(nil), "reservation.Reservation")
	proto.RegisterType((*ReserveRequest)(nil), "reservation.ReserveRequest")
	proto.RegisterType((*ReserveResponse)(nil), "reservation.ReserveResponse")
	proto.RegisterType((*IdRequest)(nil), "reservation.IdRequest")
	proto.RegisterType((*ActiveReservationsResponse)(nil), "reservation.ActiveReservationsResponse")
}

func init() {
	proto.RegisterFile("pkg/reservation/reservation.proto", fileDescriptor_7c6c6658ff475ba8)
}

var fileDescriptor_7c6c6658ff475ba8 = []byte{
	// 514 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xd1, 0x8e, 0x93, 0x40,
	0x14, 0x5d, 0xa8, 0xb6, 0xee, 0xad, 0x76, 0x71, 0x1e, 0x94, 0x6d, 0x75, 0xb7, 0x92, 0x18, 0xeb,
	0xc6, 0x40, 0x52, 0xa3, 0x51, 0xe3, 0x4b, 0x6d, 0x59, 0x25, 0x31, 0xdd, 0x0d, 0x65, 0xf7, 0x61,
	0x13, 0x25, 0xb4, 0x33, 0x45, 0xa2, 0x30, 0xc8, 0x0c, 0xfb, 0xe0, 0x37, 0xf8, 0x01, 0x26, 0xfe,
	0xac, 0xd9, 0xa1, 0xb4, 0x83, 0x52, 0x7d, 0xf1, 0x0d, 0xce, 0x3d, 0xe7, 0x9e, 0x3b, 0xe7, 0x32,
	0xc0, 0x83, 0xf4, 0x73, 0x68, 0x65, 0x84, 0x91, 0xec, 0x32, 0xe0, 0x11, 0x4d, 0xe4, 0x67, 0x33,
	0xcd, 0x28, 0xa7, 0xa8, 0x2d, 0x41, 0xdd, 0xc3, 0x90, 0xd2, 0xf0, 0x0b, 0xb1, 0x44, 0x69, 0x9e,
	0x2f, 0x2d, 0x1e, 0xc5, 0x84, 0xf1, 0x20, 0x4e, 0x0b, 0xb6, 0xf1, 0x5d, 0x85, 0xb6, 0xbb, 0x11,
	0xa0, 0xc7, 0xa0, 0x05, 0x8b, 0x05, 0x8d, 0x63, 0x8a, 0x05, 0xe0, 0x47, 0x58, 0x57, 0xfa, 0xca,
	0xa0, 0xe1, 0xee, 0x55, 0x70, 0x07, 0xa3, 0x97, 0x00, 0x8c, 0x07, 0x19, 0xf7, 0x71, 0xc0, 0x89,
	0xae, 0xf6, 0x95, 0x41, 0x7b, 0xd8, 0x35, 0x0b, 0x43, 0xb3, 0x34, 0x34, 0xbd, 0xd2, 0xd0, 0xdd,
	0x15, 0xec, 0x49, 0xc0, 0x09, 0x7a, 0x06, 0x37, 0x48, 0x82, 0x0b, 0x61, 0xe3, 0x9f, 0xc2, 0x16,
	0x49, 0xb0, 0x90, 0x0d, 0x40, 0x4b, 0xf2, 0x78, 0x4e, 0x32, 0x9f, 0x2e, 0xfd, 0x30, 0x27, 0x8c,
	0x33, 0xfd, 0x9a, 0x18, 0xae, 0x53, 0xe0, 0x27, 0xcb, 0xb7, 0x02, 0x45, 0xcf, 0xa1, 0xc9, 0x78,
	0xc0, 0x73, 0xa6, 0x5f, 0xef, 0x2b, 0x83, 0xce, 0xf0, 0xc0, 0x94, 0x83, 0x92, 0x0e, 0x3c, 0x13,
	0x2c, 0x77, 0xc5, 0x36, 0x08, 0x74, 0x8a, 0x22, 0x71, 0xc9, 0xd7, 0xab, 0x56, 0xe8, 0x2e, 0xb4,
	0x72, 0x46, 0xb2, 0x4d, 0x0e, 0xcd, 0xab, 0x57, 0x07, 0xa3, 0x57, 0x20, 0x27, 0xbd, 0x3a, 0xbf,
	0xbe, 0xcd, 0xc7, 0x95, 0xc9, 0xc6, 0x0b, 0xd8, 0x5b, 0xdb, 0xb0, 0x94, 0x26, 0x8c, 0xa0, 0x87,
	0xd0, 0x91, 0x18, 0x1b, 0xbb, 0x5b, 0x12, 0xea, 0x60, 0xa3, 0x07, 0xbb, 0x0e, 0x2e, 0x67, 0xeb,
	0x80, 0xba, 0xe6, 0xa9, 0x11, 0x36, 0x2e, 0xa0, 0x3b, 0x5a, 0xf0, 0x48, 0x74, 0x2d, 0x35, 0x6c,
	0xed, 0xf0, 0x1a, 0x6e, 0x4a, 0xbd, 0x98, 0xae, 0xf4, 0x1b, 0x7f, 0x9d, 0xb8, 0xc2, 0x3e, 0xfa,
	0xa1, 0xc0, 0xed, 0x3f, 0x72, 0x43, 0x06, 0x1c, 0xb8, 0xf6, 0xcc, 0x76, 0xcf, 0x47, 0x9e, 0x73,
	0x32, 0xf5, 0x67, 0xde, 0xc8, 0x3b, 0x9b, 0xf9, 0x67, 0xd3, 0xd9, 0xa9, 0x3d, 0x76, 0x8e, 0x1d,
	0x7b, 0xa2, 0xed, 0xa0, 0xfb, 0xb0, 0x5f, 0xc3, 0x19, 0x8d, 0x3d, 0xe7, 0xdc, 0xd6, 0x14, 0x74,
	0x08, 0xbd, 0xda, 0xf2, 0xd8, 0x3e, 0xf5, 0xec, 0x89, 0xa6, 0x6e, 0x21, 0x4c, 0xec, 0xf1, 0x7b,
	0x67, 0x6a, 0x4f, 0xb4, 0xc6, 0xf0, 0xa7, 0x0a, 0x48, 0x1e, 0x8d, 0x64, 0x97, 0xd1, 0x82, 0xa0,
	0x63, 0x68, 0xad, 0x42, 0x46, 0xbd, 0x9a, 0x43, 0x96, 0x1b, 0xee, 0xde, 0xab, 0x2f, 0x16, 0xa9,
	0x19, 0x3b, 0xe8, 0x23, 0xec, 0x8b, 0x54, 0x03, 0x5e, 0xc9, 0x55, 0x7c, 0x69, 0xe8, 0x4e, 0x45,
	0xbc, 0x5e, 0x4d, 0xf7, 0x51, 0x05, 0xdf, 0xbe, 0x15, 0x63, 0x07, 0x7d, 0x00, 0xbd, 0xae, 0xff,
	0x3b, 0xfa, 0x5f, 0xda, 0xbf, 0x79, 0x72, 0x71, 0x14, 0x46, 0xfc, 0x53, 0x3e, 0x37, 0x17, 0x34,
	0xb6, 0xf0, 0x37, 0x9a, 0x44, 0x34, 0x65, 0x96, 0xb8, 0xcb, 0x89, 0xf5, 0xdb, 0xff, 0x64, 0xde,
	0x14, 0xf7, 0xef, 0xe9, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x93, 0x16, 0x6b, 0x88, 0x69, 0x04,
	0x00, 0x00,
}
